[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35.1", features = ["bundled"] }

glfw = "0.42.0"
glium = "0.30.2"
imgui = "0.8.0"

nalgebra-glm = "0.15.0"

toml = "0.5.8"

enum-map = "1.1.1"
strum = "0.22.0"
strum_macros = "0.22"

scheduled-thread-pool = "0.2.5"
