[package]
name = "omt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

toml = "0.5.8"
image = "0.23.14"
nalgebra-glm = "0.16.0"
ncollide2d = "0.32.0"
